### ISSUE TITLE
6.7.4 的包会崩溃！

### ISSUE THREAD

**Issue by anru1314** [DKWechatHelper/DKWechatHelper#1]
大佬，只能运行7以上的版本吗？

**Comment by DKJone** [comment]
是的，微信7.0修改了很多内容，插件基于微信7.0开发，7.0之前的微信部分函数不存，在运行的时候会崩溃，如果你需要在7.0之前的版本使用推荐你使用[WeChatRedEnvelop](https://github.com/buginux/WeChatRedEnvelop)

**Comment by anru1314** [comment]
@DKJone 好的，谢谢。可是面对高版本的微信，使用插件抢红包应该很容易被封号吧？

**Comment by DKJone** [comment]
@anru1314 源码里有一部分的防封号的逻辑在dkhelperDylib.m里，另外你下载全部源码后用XCode安装的bundleID就是“com.tencent.xin”。这些都是防止微信检测的，但是不是绝对的安全，还是可以被微信检测出来的。
