### ISSUE TITLE
无法调试。但是能安装上。

### ISSUE THREAD

**Issue by yangsunyue** [DKWechatHelper/DKWechatHelper#108]
<img width="260" alt="WX20220531-150644@2x" src="https://user-images.githubusercontent.com/26077624/171113203-2d4ab815-b53e-4cf3-a552-029989f6ad5a.png">

Recovery Suggestion: A binary with bundle identifier “com.dkjone.heplerpanpanda” is installed but it is different from the bundle identifier “com.tencent.xin” that Xcode is asked to launch. Try closing and reopening the project.

**Comment by DKJone** [comment]
monkedev 和新xcode问题，跟项目没有关系command+shift+k 重新编译
