### ISSUE TITLE
是否有办法实现关闭后台后继续推送？

### ISSUE THREAD

**Issue by QiuSimons** [DKWechatHelper/DKWechatHelper#11]
百度看到之前有个叫24k黑钻的版本可以关闭后台后继续推送，请问原理是什么？原则上重新签名以后不是应该不能推送了么

**Comment by DKJone** [comment]
在微信运行的时候可以收到推送，如果你打开后台抢红包，只要不直接杀死，微信会一直在后台运行，也可以收到推送，不打开后台会在退出几秒钟后收不到推送。杀死进程的话，目前无法继续推送。推送证书和bundleID绑定的我目前还不知道更换BundleID不换推送证书的方法。
