### ISSUE TITLE
安装不进去，提示如下

### ISSUE THREAD

**Issue by gu2890961** [DKWechatHelper/DKWechatHelper#13]
This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.

**Comment by gu2890961** [comment]
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/12827815/52942198-7fe75c00-33a5-11e9-92c1-97d99668b5cf.png">

**Comment by DKJone** [comment]
这是无法覆盖微信，你可以修改build setting中的MONKEYDEV_DEFAULT_BUNDLEID为NO然后配置你的bundleId和签名证书信息

**Comment by gu2890961** [comment]
可以了，非常感谢
