### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by CivelXu** [DKWechatHelper/DKWechatHelper#4]
/Users/xuxiwen/Library/Developer/Xcode/DerivedData/dkhelper-gawoykyoftmbchesarccblkiulia/Build/Intermediates.noindex/dkhelper.build/Debug-iphoneos/dkhelperDylib.build/Script-114CCC3321F817D500A4646E.sh: line 2: /opt/MonkeyDev/bin/md: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by DKJone** [comment]
面向越狱开发的，需要安装monkeydev在文章最下方有链接

**Comment by CivelXu** [comment]
好的, 谢谢了,想问一下 ipa 文件一般的获取路径是通过什么方式?

**Comment by DKJone** [comment]
通过各种助手(pp助手，爱思助手。。。)下载越狱版的应用，或者自己通过越狱了的手机获取

**Comment by CivelXu** [comment]
我刚刚用 App Singer 重签了 其他的 App 安装到手机打开闪退；非越狱设备，大神知道为什么吗？

发自我的 iPhone

**Comment by DKJone** [comment]
应该是你选的账号和签名的bundleid不对应，你可以去开发者网站配置后下载签名的配置文件直接拖到app siger里就可以了

**Comment by CivelXu** [comment]
我是App Store的 ipa, 是需要砸壳吗, 有没有一些简单上手的工具
