### ISSUE TITLE
编译执行的时候报错，用的是作者百度云提供的砸壳后的包

### ISSUE THREAD

**Issue by Mcdull0921** [DKWechatHelper/DKWechatHelper#5]
DKHelper.m源码的58行，报这个错误：
Multiple methods named 'initWithFrame:style:' found with mismatched result, parameter type or attributes，这个是砸壳的微信包不对吗？用的是作者百度云提供的下载

**Comment by DKJone** [comment]
@Mcdull0921 编译和调试都要选择真实的IOS设备

**Comment by DKJone** [comment]
<img width="1237" alt="2019-01-27 3 33 16" src="https://user-images.githubusercontent.com/15855089/51798159-2af27300-2249-11e9-8cc2-7af9baf3dd1e.png">

**Comment by Mcdull0921** [comment]
成功了，谢谢作者，已打赏，希望以后能多更新防检测
