### ISSUE TITLE
抢红包功能不好用

### ISSUE THREAD

**Issue by DKJone** [DKWechatHelper/DKWechatHelper#6]
抢红包功能不好用

_Originally posted by @qibaozhen in https://github.com/DKWechatHelper/DKWechatHelper/issues/2#issuecomment-458046892_

**Comment by qibaozhen** [comment]
打开所有开关，发红包 别不能自动抢 尝试修改代码 未能成功

**Comment by DKJone** [comment]
@qibaozhen  自动抢红包是只会抢群聊中的红包

**Comment by popking5466** [comment]
我设置了好像不能抢群里的红包,发了两个没响应,但是自动抢红包已经设置打开了,延迟600ms
