### ISSUE TITLE
onRevokeMsg 取不到 revokemsg 

### ISSUE THREAD

**Issue by Guodadada** [DKWechatHelper/DKWechatHelper#8]
onRevokeMsg 取不到 revokemsg

**Comment by DKJone** [comment]
要获取到消息内容的前提条件是本地已经接收到了那条消息，防止撤回只是在接受到撤回后没有删除本地消息，如果那条消息你没有收到，就没法拦截撤回

**Comment by Guodadada** [comment]
> 要获取到消息内容的前提条件是本地已经接收到了那条消息，防止撤回只是在接受到撤回后没有删除本地消息，如果那条消息你没有收到，就没法拦截撤回

查到原因了，自己发的信息，撤回这个方法获取不到

**Comment by Guodadada** [comment]
> 要获取到消息内容的前提条件是本地已经接收到了那条消息，防止撤回只是在接受到撤回后没有删除本地消息，如果那条消息你没有收到，就没法拦截撤回

加下微信好吗
